global_costmap:
  global_frame: odom  # If not using a map, ensure it is odom
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: false   # Ensure this is false if not using a pre-made map
  rolling_window: true
  width: 10.0         # Ensure this covers enough area
  height: 10.0
  resolution: 0.05
